weather/urls.py
from django.urls import path
from weather.views import HomePageView, ArchiveView, ForecastView

app_name = 'weather'

urlpatterns = [
    path('', HomePageView.as_view(), name='homepage'),
    path('archive', ArchiveView.as_view(), name='archive'),
    path('forecast', ForecastView.as_view(), name='forecast'),
]

weather_portal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('weather.urls', namespace='weather')),
]

weather/models.py
from django.db import models
from django.utils.safestring import mark_safe


class CityWeatherInfo(models.Model):
    class Meta:
        unique_together = [('city_name', 'date')]

    city_name = models.CharField(max_length=30)
    date = models.DateField(auto_now_add=True)
    country_code = models.CharField(max_length=30)
    weather_description = models.CharField(max_length=30)
    temp = models.FloatField()
    temp_feels_like = models.FloatField()
    temp_min = models.FloatField()
    temp_max = models.FloatField()
    icon = models.CharField(max_length=20)

    @property
    def icon_preview(self):
        return mark_safe(f'<img src="http://openweathermap.org/img/w/{self.icon}.png" alt="Image" style="width:60px">')

weather/forms.py
from django import forms


class CityForm(forms.Form):
    city = forms.CharField(required=True)


class ArchiveForm(forms.Form):
    city = forms.CharField(required=False)
    date_from = forms.DateField(required=False, help_text='yyyy-mm-dd')
    date_to = forms.DateField(required=False, help_text='yyyy-mm-dd')


class ForecastForm(forms.Form):
    city = forms.CharField(required=True)

weather/views.py
from django.db import IntegrityError
from django.db.models import QuerySet
from django.utils.dateparse import parse_date
from django.shortcuts import redirect
from django.utils import timezone
from django.views.generic import FormView, ListView

from utils import add_url_params
from weather.forms import CityForm, ArchiveForm, ForecastForm
from weather.models import CityWeatherInfo
from weather.services.open_weather_map import OpenWeatherClient, OpenWeatherError


class HomePageView(FormView):

    template_name = 'weather/home_page.html'
    form_class = CityForm

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.client_weather = OpenWeatherClient()

    def form_valid(self, form: CityForm):
        name_city = form.cleaned_data['city']
        error = None
        weather = None
        try:
            weather = CityWeatherInfo.objects.get(city_name__iexact=name_city, date=timezone.now().date())
        except CityWeatherInfo.DoesNotExist:
            try:
                weather = self._get_weather(name_city)
            except OpenWeatherError:
                error = 'Could not get information about weather.'
        return self.render_to_response(self.get_context_data(weather=weather, error=error))

    def _get_weather(self, city: str) -> CityWeatherInfo:
        raw_weather = self.client_weather.get_city_weather(city)
        weather = self.client_weather.parse_weather(raw_weather)
        try:
            weather.save()
        except IntegrityError:
            pass
        return weather


class ArchiveView(FormView, ListView):

    template_name = 'weather/archive.html'
    form_class = ArchiveForm
    model = CityWeatherInfo
    context_object_name = 'city_weathers'
    paginate_by = 5

    def form_valid(self, form: ArchiveForm):
        """
        Redirect to Archive page. Add to url parameters from form.
        """
        response = redirect('weather:archive')
        response['Location'] = add_url_params(response[ 'Location'], form.cleaned_data)
        return response

    def get_queryset(self) -> QuerySet[CityWeatherInfo]:
        queryset = super().get_queryset()
        if city := self.request.GET.get('city'):
            queryset = queryset.filter(city_name__iexact=city)
        if date_to := self.request.GET.get('date_to'):
            queryset = queryset.filter(date__lte=parse_date(date_to))
        if date_from := self.request.GET.get('date_from'):
            queryset = queryset.filter(date__gte=parse_date(date_from))
        return queryset

    def get_context_data(self, **kwargs):
        """
        Add url params for pagination to keep filtering.
        """
        context = super().get_context_data(**kwargs)
        context['url_params'] = add_url_params('', {
            'city': self.request.GET.get('city'),
            'date_to': self.request.GET.get('date_to'),
            'date_from': self.request.GET.get('date_from'),
        })
        return context


class ForecastView(FormView):
    template_name = 'weather/forecast.html'
    form_class = ForecastForm

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.client_weather = OpenWeatherClient()

    def form_valid(self, form: ForecastForm):
        name_city = form.cleaned_data['city']
        weather = self.client_weather.get_weather_forecast(name_city)
        return self.render_to_response(self.get_context_data(weather=weather))

templates/base.html
{% load bootstrap5 %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
    {% endblock %}
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <title>
        {% block title %}
            Title
        {% endblock %}
    </title>
</head>
<body>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% include 'header.html' %}
    <div class="container">
        {% block content %}
            <p>Content is here</p>
        {% endblock %}
    </div>
</body>
</html>

templates/header.html
<nav class="navbar navbar-light bg-dark">
  <form class="container-fluid justify-content-end">
      <a href="{% url 'weather:homepage' %}" class="btn btn-outline-light me-2 border-3" type="submit">Home</a>
      <a href="{% url 'weather:archive' %}" class="btn btn-outline-light me-2 border-3" type="submit">Archive</a>
      <a href="{% url 'weather:forecast' %}" class="btn btn-outline-light me-2 border-3" type="submit">Forecast</a>
  </form>
</nav>

templates/weather/archive.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block title %}
    Archive
{% endblock %}

{% block content %}
    <h1 class="text-center">Weather archive</h1>
    <form class="form my-5 p-2" method="post">{% csrf_token %}
        <h4>Filter</h4>
        {% bootstrap_form form %}
        <button type="submit" class="btn btn-dark justify-content-end">Select</button>
    </form>
    <table class="table table-dark table-striped">
      <thead>
        <tr>
          <th scope="col"></th>
          <th scope="col">City name</th>
          <th scope="col">Country code</th>
          <th scope="col">Temperature °C</th>
          <th scope="col">Feels like °C</th>
          <th scope="col">Max temperature °C</th>
          <th scope="col">Min temperature °C</th>
          <th scope="col">Date</th>
        </tr>
      </thead>
      <tbody>
          {% for city_weather in page_obj %}
              <tr>
                  <th scope="row">{{ page_obj.start_index|add:forloop.counter|add:-1 }}</th>
                  <td>{{ city_weather.city_name }}</td>
                  <td>{{ city_weather.country_code }}</td>
                  <td>{{ city_weather.temp }}</td>
                  <td>{{ city_weather.temp_feels_like }}</td>
                  <td>{{ city_weather.temp_max }}</td>
                  <td>{{ city_weather.temp_min }}</td>
                  <td>{{ city_weather.date }}</td>
              </tr>
          {% endfor %}
      </tbody>
    </table>

    <div>
        <div>
            {% if page_obj.has_previous %}
                <a class="btn btn-outline-dark" href="{{ url_params }}&page=1">first<i class="bi bi-caret-left-fill"></i></a>
                <a class="btn btn-outline-dark" href="{{ url_params }}&page={{ page_obj.previous_page_number }}">
                    <i class="bi bi-arrow-left-circle-fill"></i>
                </a>
            {% endif %}
            <span class="current" style="font-family: 'Comic Sans MS',monospace">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>
            {% if page_obj.has_next %}
                <a class="btn btn-outline-dark" href="{{ url_params }}&page={{ page_obj.next_page_number }}">
                    <i class="bi bi-arrow-right-circle-fill"></i>
                </a>
                <a class="btn btn-outline-dark" href="{{ url_params }}&page={{ page_obj.paginator.num_pages }}">last<i class="bi bi-caret-right-fill"></i></a>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/weather/forecast.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% load grouping %}

{% block title %}
    Forecast
{% endblock %}

{% block content %}
    <h1 class="text-center" style="font-family: 'Comic Sans MS', serif ">Would you like to know future?</h1>
    <h3 class="text-center" style="font-family: fantasy ">weather forecast for 5 days with data every 3 hours by city name</h3>
    <form class="form text-center my-5 p-2" method="post">{% csrf_token %}
        {% bootstrap_form form %}
        <button type="submit" class="btn btn-dark justify-content-end">Select</button>
    </form>
    {% if weather %}
        <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-indicators">
                {% for j in weather %}
                    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="{{ forloop.counter0 }}" class="active" aria-current="true" aria-label="Slide 1"></button>
                {% endfor %}
            </div>
                <div class="carousel-inner">
                  {% for group in weather|grouping_by_n:8 %}
                        <div class="carousel-item {% if forloop.counter0 == 0 %}active{% endif %} ">
                            <div class="row">
                                {% for info in group %}
                                    <div class="col">
                                        <div class="card" style="width: 18rem">
                                            <div class="card-body">
                                                <h3>{{ info.date }}</h3>
                                                <h1>{{ info.description|capfirst }}</h1>
                                                <img src="https://openweathermap.org/img/w/{{ info.icon }}.png" alt="Image" style="width:60px">
                                                <h1 style="color: green">{{ info.temperature }} °C</h1>
                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                  {% endfor %}
                </div>
          <button class="carousel-control-prev" style="background-color: gainsboro" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>
          <button class="carousel-control-next" style="background-color: gainsboro" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </button>
        </div>
    {% endif %}
{% endblock %}

templates/weather/home_page.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block title %}

    {% if weather.city_name %}
        {{ weather.city_name }} weather
    {% else %}
        City weather
    {% endif %}

{% endblock %}

{% block content %}
    <h1 class="text-center">What about the weather?</h1>
    <form class="form text-center my-5 p-2" method="post">{% csrf_token %}
        {% bootstrap_form form %}
        <button type="submit" class="btn btn-dark justify-content-end">Select</button>
    </form>

    {% if error %}
        <h3 class="alert-danger">{{ error }}</h3>
    {% endif %}

    {% if weather %}
        <div class="card text-center mx-5">
            <div class="card-header">
                <h3>{{ weather.city_name }} <i class="bi bi-geo-alt"></i>{{ weather.country_code }}</h3>
            </div>
            <div class="card-body">
                <h1 class="card-title">
                    {{ weather.weather_description|capfirst }}
                    {{ weather.icon_preview }}
                </h1>
                <h2 class="card-text">
                    Feels like: <i class="bi bi-thermometer"></i>{{ weather.temp_feels_like }}
                </h2>
                <h4 class="card-text" style="font-family: cursive">
                    min<i class="bi bi-thermometer"></i>{{ weather.temp_min }}
                    <span style="font-size: 45px; color: green"><i class="bi bi-thermometer"></i>{{ weather.temp }}</span>

                    max<i class="bi bi-thermometer"></i>{{ weather.temp_max }}
                </h4>
            </div>
                <div class="card-footer text-muted">
            </div>
        </div>
    {% endif %}
{% endblock %}